# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xH6a6tQlQmvZzmpm-_QET6MWP9THydnG
"""

my_test={}
print(type(my_test))

my_test1=dict()
print(type(my_test1))

attr_dict={"name":"Abhi","age":19}
print(attr_dict)
print(type(attr_dict))

for key in attr_dict:
    print(key)

for value in attr_dict.values():
    print(value)

for a,b in attr_dict.items():
    print(a,b)

# Create a dict with default values
deft=dict.fromkeys(["name","age"],"NA")
print(deft)

# Get the value associated with a key using the dict.get() method with a default value.
print(attr_dict.get("name"),"shek")

test="Helllloo"
count_test={}
for i in test:
  count_test[i]=count_test.get(i,0) +1
print(count_test)


attr_dict={"name":"Abhi","age":19,"name":"Abhi"}
for keys in attr_dict:
  print(attr_dict.get(keys,0))