# -*- coding: utf-8 -*-
"""lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YClqnZTQOaOYEs-pRYmf5upg3jjnhUUP

List are ordered, mutable and allows duplcates.
<------------>
List have positive and negative indexing
<------------>
Slicing: my_list[2: -2] -- if we want to access a portion of a list, we use slice operator :
If you omit the start index, the slicing starts from the first element. Similarly, if you omit the last index, the slicing ends at the last element.
<------------>
Add Elements to a Python List
fruits.append('cherry') -- it adds the element to the end of the list.
<------------>
Add Elements at the Specified Index
fruits.insert(2, 'cherry')
<------------>
Add Elements to a List From Other Iterables
numbers = [1, 3, 5]
even_numbers  = [2, 4, 6]
numbers.extend(even_numbers)
<------------>
Change List Items using = assignment operator
colors[2] = 'Blue'
<------------>
Remove an Item From a List
numbers.remove(4) -- it is not the index but the value
<------------>
The list pop() method removes the item at the specified index. The method also returns the removed item.
<------------>
Remove One or More Elements of a List
names = ['John', 'Eva', 'Laura', 'Nick', 'Jack']

# delete the item at index 1
del names[1]
print(names)

# delete items from index 1 to index 2
del names[1: 3]
print(names)

# delete the entire list
del names
<----------->
Method	Description
append()	Adds an item to the end of the list
extend()	Adds items of lists and other iterables to the end of the list
insert()	Inserts an item at the specified index
remove()	Removes the specified value from the list
pop()	Returns and removes item present at the given index
clear()	Removes all items from the list
index()	Returns the index of the first matched item
count()	Returns the count of the specified item in the list
sort()	Sorts the list in ascending/descending order
reverse()	Reverses the item of the list
copy()	Returns the shallow copy of the list
<----------->
sort() Syntax
numbers.sort(reverse, key)
The sort() method can take two optional keyword arguments:

reverse - By default False. If True is passed, the list is sorted in descending order.
key - Comparion is based on this function.
<----------->
List comprehension makes the code cleaner and more concise than for loop
numbers = [1, 2, 3, 4]
# list comprehension to create new list
doubled_numbers = [num * 2 for num in numbers]

word = "Python"
vowels = "aeiou"

# find vowel in the string "Python"
result = [char for char in word if char in vowels]

print(result)

# Output: ['o']
<---------->
Syntax of List Comprehension
[expression for item in list if condition == True]
# filtering even numbers from a list
even_numbers = [num for num in range(1, 10) if num % 2 == 0 ]
print(even_numbers)
# Output: [2, 4, 6, 8]
<---------->
"""

list=[1,7,-10,34,2,-8]
sum=0
for num in list:
	sum+=num
print(sum)

list=[3,4,5,4,7]
product=1
for i in list:
    product*=i
print(product)

list=[1,7,10,34,2,8]
list.sort()
print(list[-1])

# or
list2=[1,7,10,34,2,8]
list2.sort(reverse=True)
print(list2[0])

list=[51,7,10,34,2,8]
list.sort()
print(list[0])

"""Breakdown of problem:
1. requirement to find the cound of str len of 2 or more.
2. the first and last char should be same of the strings
"""

list=['abc', 'xyz', 'aba', '1221']
count=0
for i in list:
  if len(i)>1 and i[0]==i[-1]:
    count+=1
print(count)

list=[1,2,3,7,2,1,5,6,4,8,5,4]
# duplicate_list=[num for num in list if list.count(num)>1]
# print(duplicate_list)
# to remove all the aoccurence of duplicates except the first iteration
final_list=[]
for num in list:
  if list.count(num)>1 and num not in final_list:
    final_list.append(num)
  elif list.count(num)==1:
    final_list.append(num)
  else:
    print("duplicate entry coming {0}".format(num))
final_list.sort()
print(final_list)

list=[1,2,3,7,2,1,5,6,4,8,5,4]
inal_list=[]
for num in list:
  if num not in final_list:
    final_list.append(num)

print(final_list)

# prompt: Most effieceint way to solve  Write a Python program to remove duplicates from a list
# Sample Output
# [1,2,3,7,2,1,5,6,4,8,5,4]

def remove_duplicates(input_list):
  """Removes duplicates from a list while preserving order.

  Args:
    input_list: The list to remove duplicates from.

  Returns:
    A new list with duplicates removed, preserving the original order.
  """
  seen = set()
  result = []
  for item in input_list:
    if item not in seen:
      seen.add(item)
      result.append(item)
  return result

# Example usage
my_list = [1, 2, 3, 7, 2, 1, 5, 6, 4, 8, 5, 4]
unique_list = remove_duplicates(my_list)
unique_list

list=[34,45,6,5,4,56,7]
if len(list)==0:
  print("list is empty")
else:
  print("List is not empty")

old_list = [10, 22, 44, 23, 4]
new_list = old_list
print(new_list)

list=['Words', 'Longer', 'given', 'Words']
count=0
for i in list:
  if len(i)>4:
    count+=1

print("the words having len > 4 are {0}".format(count))

list1=[1,2,3,4,5,3,4]
list2=[5,6,7,8,9,3,4]
common_value=[]
a=set(list2)
result=False
for i in list1:
  if(i in list2 and i not in common_value):
    print("there are common value: {0}".format(i))
    result=True
    common_value.append(i)

print(result)
#To modify and show a list of common values without duplicates
print(common_value)

list=["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]
NEW_LIST=[value for index,value in enumerate(list) if index not in [0,4,5]]
print(NEW_LIST)

list=[7,32,81,20,25,14,23,27]
new_list=[value for value in list if value%2!=0 ]
print(new_list)
"""or
for i in list:
  if i%2==0:
    list.remove(i)

print(list)"""

from random import shuffle
list=["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]
random.shuffle(list)
print(list)

list=[value*value for value in range(1,31)]
first_five=list[:5]
last_five=list[-5:]
print(first_five)
print(last_five)

import itertools as itere
list_one=[1,2,3]
perms=itere.permutations(list_one)
print(type(perms))
for i in perms:
  print(i)

list=['T','u','t','o','rsdf',' ','J','o','e','s']
s1=''.join(list)
print(s1)

list=[20, 70, 30, 90, 10, 30, 90, 10, 80]
print(list.index(30))

#18
list=[[20,30,70],[30,90,10], [30,20], [70,90,10,80],'joh']
#Todo: Convert the list of list into a single list
list_new=[]
for i in list:
  if len(i) > 1:
    for j in i:
      list_new.append(j)
  else:
    list_new.append(i)

print(list_new)

new_list=[item for sublist in list for item in sublist]
print(new_list)

Number = [10, 20, 30, 40]
animal = ["Cat", "Dog", "Lion", "Ponda"]
final_list=(Number) + (animal)
print(final_list)
print(Number)

import random
list=["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]
print(random.choice(list))

list1=[8, 8, 12, 12, 8]
list2=[8, 8, 8, 12, 12]
if len(list1)==len(list2):
  print("List are of same length")
else:
  print("lists are of different length")
  exit
var_list=False
concatendated_list=list1*2
print(concatendated_list)
for i in range(len(list1)):
  if(concatendated_list[i:i+len(list2)]==list2):
    print("The combination matches")
    var_list=True
    print(var_list)
  else:
    print("The combination does not match")

list=[2,4,56,78,4,34,5,8,9]
new_list=[]
list.sort(reverse=True)
print(list)
for i in list:
  if(i > new_list[i]):
    new_list.append(i)
  else:
    print("nothing")

#second smallest
list=[2,4,56,78,4,34,5,8,9]
first=second = 2
for i in list:
  if i < first:
    second = first
    first = i
  elif(first < i < second):
    second = i
print(second)
print(first)

list=[2,4,56,78,4,34,5,8,9]
#Find the largest number
first=second=0
for i in list:
  if i > first:
    second=first
    first=i
  elif first > i > second:
    second=i
print(first)
print(second)

my_list=[82, 4, 10, 56, 78, 4, 34, 5, 10, 9]
#unique values
s1=set(my_list)
new_test = list(s1)
print(new_test)

my_list=[10, 30, 50, 10, 20, 60, 20, 60, 40, 40, 50, 50, 30]
s1=set(my_list)
#output: Counter({50: 3, 10: 2, 30: 2, 20: 2, 60: 2, 40: 2})
#Todo: Use a for loop and count the freq and keep addding the num, fre as a key value pair in a dictonary
new_dic={}
for i in my_list:
  new_dic[i]=1
  if i in new_dic.keys():
    new_dic[i]=new_dic[i] + 1
  else:
    print("element not present in list")

print(new_dic)

from collections import Counter
my_list=[10, 30, 50, 10, 20, 60, 20, 60, 40, 40, 50, 50, 30]
count=Counter(my_list)
print(count)

# Python program to demonstrate
# defaultdict


from collections import defaultdict


# Defining the dict
d = defaultdict(int)

L = [1, 2, 3, 4, 2, 4, 1, 2]

# Iterate through the list
# for keeping the count
for i in L:

    # The default value is 0
    # so there is no need to
    # enter the key first
    d[i] += 1

print(d)

my_list=[]
con_list=['T','J']
for i in range(1,10):
  for j in con_list:
    my_list.append(j+str(i))

print(my_list)